import 'asm_registry.dart';

/// Bit layout of the IMO 001/0 free-text messages ("Text using 6-bit ASCII" /
/// "Text telegram"), used on message types 6, 8, 25 and 26. The trailing text
/// is variable-width 6-bit ASCII (typed directly in the editor).
const List<AsmField> _kTextMsgFields = [
  AsmField('type', 'Message Type', 6),
  AsmField('repeat', 'Repeat Indicator', 2),
  AsmField('mmsi', 'Source MMSI', 30),
  AsmField('spare', 'Spare', 2),
  AsmField('dac', 'DAC', 10),
  AsmField('fid', 'FID', 6),
  AsmField('ack', 'Acknowledge required flag', 1),
  AsmField('seq', 'Text sequence number', 11),
  AsmField('text', 'Text', 936, kind: AsmFieldKind.freeText),
];

/// Complete ASM catalog compiled from the e-Navigation.nl AIS ASM
/// collection (https://www.e-navigation.nl/asm/ais), the gpsd AIVDM
/// documentation and the IALA ASM collection. Duplicate DAC/FID pairs
/// (different versions / registrants) are kept on purpose.
///
/// Entries with a documented bit layout carry a non-empty [fields]
/// list (see the gpsd AIVDM reference); the others are edited as raw
/// Data bytes.
const List<AsmFormat> kAsmFormats = [
  AsmFormat(
    dac: 0,
    fid: 0,
    name: "Monitoring aids to navigation",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "Zeni Lite Buoy Co., Ltd",
    permittedAsFrom: "01/03/2002",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence Number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('sub_application_id', 'Sub-application ID', 16),
      AsmField('voltage_data', 'Voltage Data', 12),
      AsmField('current_data', 'Current Data', 10),
      AsmField('power_supply_type', 'Power Supply Type', 1),
      AsmField('light_status', 'Light Status', 1),
      AsmField('battery_status', 'Battery Status', 1),
      AsmField('off_position_status', 'Off Position Status', 1),
      AsmField('spare_1', 'Spare', 6),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 0,
    name: "Text telegram using 6-bit ASCII",
    types: [6],
    fields: _kTextMsgFields,
    sub: 5,
    state: AsmState.replaced,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    notToBeUsedAfter: "15/06/2007",
    deprecatedSince: "not to be used after 15/06/2007",
  ),  AsmFormat(
    dac: 1,
    fid: 0,
    name: "Text using 6-bit ASCII",
    types: [6],
    fields: _kTextMsgFields,
    sub: 5,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-3",
    permittedAsFrom: "16/06/2007",
  ),  AsmFormat(
    dac: 1,
    fid: 1,
    name: "Application acknowledgement",
    types: [6],
    sub: 1,
    state: AsmState.replaced,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    notToBeUsedAfter: "01/04/2010",
    deprecatedSince: "not to be used after 01/04/2010",
  ),  AsmFormat(
    dac: 1,
    fid: 2,
    name: "Interrogation for specified FMs within the IAI branch",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('requested_dac_code', 'Requested DAC code', 10),
      AsmField('requested_fi_code', 'Requested FI code', 6),
      AsmField('spare_bits', 'Spare bits', 64),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 3,
    name: "Capability interrogation",
    types: [6],
    sub: 1,
    state: AsmState.replaced,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    notToBeUsedAfter: "15/06/2007",
    deprecatedSince: "not to be used after 15/06/2007",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('requested_dac_code', 'Requested DAC code', 10),
      AsmField('spare_bits', 'Spare bits', 70),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 3,
    name: "Capability interrogation",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-3",
    permittedAsFrom: "16/06/2007",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('requested_dac_code', 'Requested DAC code', 10),
      AsmField('spare_bits', 'Spare bits', 70),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 4,
    name: "Capability reply",
    types: [6],
    sub: 1,
    state: AsmState.replaced,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    notToBeUsedAfter: "15/06/2007",
    deprecatedSince: "not to be used after 15/06/2007",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('dac_code', 'DAC code', 10),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 4,
    name: "Capability reply",
    types: [6],
    sub: 2,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-3",
    permittedAsFrom: "16/06/2007",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('dac_code', 'DAC code', 10),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 5,
    name: "Application acknowledgement to an addressed binary message",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "ITU.R-M.1371-4",
    permittedAsFrom: "01/04/2010",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('dac_code_of_received_fm', 'DAC code of received FM', 10),
      AsmField('fi_code_of_received_fm', 'FI code of received FM', 6),
      AsmField('text_sequence_number', 'Text sequence number', 11, kind: AsmFieldKind.text6),
      AsmField('ai_available', 'AI available', 1),
      AsmField('ai_response', 'AI response', 3),
      AsmField('spare_bits', 'Spare bits', 49),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 12,
    name: "Dangerous cargo indication",
    types: [6],
    sub: 2,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "01/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('lastport', 'Last Port Of Call', 30, kind: AsmFieldKind.text6),
      AsmField('lmonth', 'ETA month (UTC)', 4),
      AsmField('lday', 'ETA day (UTC)', 5),
      AsmField('lhour', 'ETA hour (UTC)', 5),
      AsmField('lminute', 'ETA minute (UTC)', 6),
      AsmField('nextport', 'Next Port Of Call', 30, kind: AsmFieldKind.text6),
      AsmField('nmonth', 'ETA month (UTC)', 4),
      AsmField('nday', 'ETA day (UTC)', 5),
      AsmField('nhour', 'ETA hour (UTC)', 5),
      AsmField('nminute', 'ETA minute (UTC)', 6),
      AsmField('dangerous', 'Main Dangerous Good', 120, kind: AsmFieldKind.text6),
      AsmField('imdcat', 'IMD Category', 24, kind: AsmFieldKind.text6),
      AsmField('unid', 'UN Number', 13),
      AsmField('amount', 'Amount of Cargo', 10),
      AsmField('unit', 'Unit of Quantity', 2),
      AsmField('spare', 'Spare', 3),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 14,
    name: "Tidal window",
    types: [6],
    sub: 3,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "01/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('month', 'Month', 4),
      AsmField('day', 'Day', 5),
      AsmField('tidals', 'Tidals', 97),
      AsmField('lat', 'Latitude', 27, kind: AsmFieldKind.signed),
      AsmField('lon', 'Longitude', 28, kind: AsmFieldKind.signed),
      AsmField('from_hour', 'From UTC Hour', 5),
      AsmField('from_min', 'From UTC Minute', 6),
      AsmField('to_hour', 'To UTC Hour', 5),
      AsmField('to_min', 'To UTC Minute', 6),
      AsmField('cdir', 'Current Dir. Predicted', 9),
      AsmField('cspeed', 'Current Speed Predicted', 7),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 16,
    name: "Number of persons on board",
    types: [6],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "17/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('persons', '# persons on board', 14),
      AsmField('spare', 'Spare', 3),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 16,
    name: "Number of persons on board",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('persons', '# persons on board', 14),
      AsmField('spare', 'Spare', 3),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 17,
    name: "Ship waypoints (WP) and/or route plan report",
    types: [6],
    sub: 5,
    state: AsmState.deprecated,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
  ),  AsmFormat(
    dac: 1,
    fid: 18,
    name: "Advice of waypoints (AWP) and/or route plan of VTS",
    types: [6],
    sub: 5,
    state: AsmState.deprecated,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    notToBeUsedAfter: "01/01/1998",
    deprecatedSince: "not to be used after 01/01/1998",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence Number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('iai', 'IAI', 16),
      AsmField('message_linkage_id', 'Message Linkage ID', 10, kind: AsmFieldKind.text6),
      AsmField('clearance_date_time_to_enter_port', 'Clearance date/time to enter port', 0, kind: AsmFieldKind.data),
      AsmField('utc_month', 'UTC Month', 4),
      AsmField('utc_day', 'UTC Day', 5),
      AsmField('utc_hour', 'UTC Hour', 5),
      AsmField('utc_minute', 'UTC Minute', 6),
      AsmField('name_of_port_and_berth', 'Name of port and berth', 120, kind: AsmFieldKind.text6),
      AsmField('destination', 'Destination', 30, kind: AsmFieldKind.text6),
      AsmField('longitude', 'Longitude', 25),
      AsmField('latitude', 'Latitude', 24),
      AsmField('spare_1', 'Spare', 43),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 18,
    name: "Clearance time to enter port",
    types: [6],
    sub: 2,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('linkage', 'Message Linkage ID', 10),
      AsmField('month', 'Month (UTC)', 4),
      AsmField('day', 'Day (UTC)', 5),
      AsmField('hour', 'Hour (UTC)', 5),
      AsmField('minute', 'Minute (UTC)', 6),
      AsmField('portname', 'Name of Port & Berth', 120, kind: AsmFieldKind.text6),
      AsmField('destination', 'Destination', 30, kind: AsmFieldKind.text6),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('spare', 'Spare', 43),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 19,
    name: "Extended ship static and voyage related data",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
  ),  AsmFormat(
    dac: 1,
    fid: 20,
    name: "Berthing data",
    types: [6],
    sub: 2,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence Number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 1),
      AsmField('iai', 'IAI', 16),
      AsmField('message_linkage_id', 'Message Linkage ID', 10, kind: AsmFieldKind.text6),
      AsmField('berth_length', 'Berth Length', 9),
      AsmField('water_depth_at_berth', 'Water Depth at Berth', 8),
      AsmField('mooring_position', 'Mooring Position', 3),
      AsmField('berth_date_and_time', 'Berth Date and Time', 0, kind: AsmFieldKind.data),
      AsmField('utc_month', 'UTC Month', 4),
      AsmField('utc_day', 'UTC Day', 5),
      AsmField('utc_hour', 'UTC Hour', 5),
      AsmField('utc_minute', 'UTC Minute', 6),
      AsmField('services_availability', 'Services availability', 1),
      AsmField('type_of_services_available', 'Type of Services Available', 52),
      AsmField('name_of_berth', 'Name of Berth', 120, kind: AsmFieldKind.text6),
      AsmField('centre_position_of_berth_longitude', 'Centre position of Berth, Longitude', 25),
      AsmField('centre_position_of_berth_latitude', 'Centre position of Berth, Latitude', 24),
      AsmField('spare_1', 'Spare', 0),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 23,
    name: "Area notice",
    types: [6],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "04/03/2011",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('message_linkage_id', 'Message Linkage ID', 10),
      AsmField('utc_month', 'UTC Month', 4),
      AsmField('max_870', 'Max 870', 0, kind: AsmFieldKind.data),
      AsmField('max_1_013', 'Max 1,013', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 25,
    name: "Dangerous cargo indication",
    types: [6],
    sub: 3,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('unit', 'Unit of Quantity', 2),
      AsmField('amount', 'Amount of Cargo', 10),
      AsmField('code', 'Cargo code', 4),
      AsmField('subtype', 'Cargo subtype', 13),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 28,
    name: "Route information",
    types: [6],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('linkage', 'Message Linkage ID', 10),
      AsmField('sender', 'Sender Class', 3),
      AsmField('rtype', 'Route Type', 5),
      AsmField('month', 'Start month (UTC)', 4),
      AsmField('day', 'Start day (UTC)', 5),
      AsmField('hour', 'Start hour (UTC)', 5),
      AsmField('minute', 'Start minute (UTC)', 6),
      AsmField('duration', 'Duration', 18),
      AsmField('waycount', 'Waycount', 5),
      AsmField('lon', 'Longitude', 28, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 27, kind: AsmFieldKind.signed),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 30,
    name: "Text description",
    types: [6],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 1,
    fid: 32,
    name: "Tidal window",
    types: [6],
    sub: 3,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('month', 'Month', 4),
      AsmField('day', 'Day', 5),
      AsmField('tidals', 'Tidals', 97),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('from_hour', 'From UTC Hour', 5),
      AsmField('from_min', 'From UTC Minute', 6),
      AsmField('to_hour', 'To UTC Hour', 5),
      AsmField('to_min', 'To UTC Minute', 6),
      AsmField('cdir', 'Current Dir. Predicted', 9),
      AsmField('cspeed', 'Current Speed Predicted', 8),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 40,
    name: "Number of persons on board",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
  ),  AsmFormat(
    dac: 200,
    fid: 3,
    name: "Inland Capability Interrogation",
    types: [6],
    sub: 0,
    version: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "18/10/2021",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('designated_area_code', 'Designated Area Code', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 4,
    name: "Inland Capability Interrogation reply",
    types: [6],
    sub: 0,
    version: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "18/10/2021",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('designated_area_code', 'Designated Area Code', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 21,
    name: "ETA at lock/bridge/terminal",
    types: [6],
    sub: 2,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('country', 'UN Country Code', 12, kind: AsmFieldKind.text6),
      AsmField('locode', 'UN/LOCODE', 18, kind: AsmFieldKind.text6),
      AsmField('section', 'Fairway section', 30, kind: AsmFieldKind.text6),
      AsmField('terminal', 'Terminal code', 30, kind: AsmFieldKind.text6),
      AsmField('hectometre', 'Fairway hectometre', 30, kind: AsmFieldKind.text6),
      AsmField('month', 'ETA month', 4),
      AsmField('day', 'ETA day', 5),
      AsmField('hour', 'ETA hour', 5),
      AsmField('minute', 'ETA minute', 6),
      AsmField('tugs', 'Assisting Tugs', 3),
      AsmField('airdraught', 'Air Draught', 12),
      AsmField('spare', 'Spare', 5),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 22,
    name: "RTA at lock/bridge/terminal",
    types: [6],
    sub: 2,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('country', 'UN Country Code', 12, kind: AsmFieldKind.text6),
      AsmField('locode', 'UN/LOCODE', 18, kind: AsmFieldKind.text6),
      AsmField('section', 'Fairway section', 30, kind: AsmFieldKind.text6),
      AsmField('terminal', 'Terminal code', 30, kind: AsmFieldKind.text6),
      AsmField('hectometre', 'Fairway hectometre', 30, kind: AsmFieldKind.text6),
      AsmField('month', 'RTA month', 4),
      AsmField('day', 'RTA day', 5),
      AsmField('hour', 'RTA hour', 5),
      AsmField('minute', 'RTA minute', 6),
      AsmField('status', 'Status', 2),
      AsmField('spare', 'Spare', 2),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 42,
    name: "Geographic Notice",
    types: [6],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "18/10/2021",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('designated_area_code', 'Designated Area Code', 0, kind: AsmFieldKind.data),
      AsmField('utc_month', 'UTC month', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 44,
    name: "ISRS Text message",
    types: [6],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "18/10/2021",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 200,
    fid: 55,
    name: "Number of persons on board",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('crew', '# crew on board', 8),
      AsmField('passengers', '# passengers on board', 13),
      AsmField('personnel', '# personnel on board', 8),
      AsmField('spare', 'Spare', 51),
    ],
  ),  AsmFormat(
    dac: 219,
    fid: 2,
    name: "Route suggestion",
    types: [6],
    sub: 5,
    state: AsmState.draft,
    registrant: "Danish Maritime Authority",
    permittedAsFrom: "03/11/2011",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence Number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('iai', 'IAI', 16),
      AsmField('message_linkage_id', 'Message Linkage ID', 10, kind: AsmFieldKind.text6),
      AsmField('route_type', 'Route Type', 5),
      AsmField('eta_first_wp', 'ETA first WP', 0, kind: AsmFieldKind.data),
      AsmField('utc_month', 'UTC Month', 4),
      AsmField('utc_day', 'UTC Day', 5),
      AsmField('utc_hour', 'UTC Hour', 5),
      AsmField('utc_minute', 'UTC Minute', 6),
      AsmField('duration', 'Duration', 18),
      AsmField('number_of_waypoints', 'Number of Waypoints', 5),
      AsmField('waypoints', 'Waypoints', 0, kind: AsmFieldKind.data),
      AsmField('spare_1', 'Spare', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 219,
    fid: 3,
    name: "Route suggestion reply",
    types: [6],
    sub: 1,
    state: AsmState.draft,
    registrant: "Danish Maritime Authority",
    permittedAsFrom: "03/11/2011",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence Number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('iai', 'IAI', 16),
      AsmField('message_linkage_id', 'Message Linkage ID', 10, kind: AsmFieldKind.text6),
      AsmField('referenced_message', 'Referenced message', 10),
      AsmField('response', 'Response', 6),
    ],
  ),  AsmFormat(
    dac: 219,
    fid: 6,
    name: "Flow management suggestion",
    types: [6],
    sub: 5,
    state: AsmState.proposal,
    registrant: "Danish Maritime Authority",
    permittedAsFrom: "04/02/2015",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('iai', 'IAI', 16),
      AsmField('wp_0_position', 'WP 0 , position', 28),
      AsmField('wp_0_eta', 'WP 0 , ETA', 5),
      AsmField('suggested_following_waypoints_with_relative_eta', 'Suggested following waypoints with relative ETA', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 235,
    fid: 10,
    name: "Aids to Navigation monitoring data",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "UK Trinity House",
    permittedAsFrom: "15/01/2009",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('ana_int', 'Analogue', 10),
      AsmField('ana_ext1', 'Analogue (ext. #1)', 10),
      AsmField('ana_ext2', 'Analogue (ext. #2)', 10),
      AsmField('racon', 'RACON status', 2),
      AsmField('light', 'Light status', 2),
      AsmField('health', 'Health', 1),
      AsmField('stat_ext', 'Status (external)', 8),
      AsmField('off_pos', 'Position status', 1),
      AsmField('spare', 'Spare', 4),
    ],
  ),  AsmFormat(
    dac: 250,
    fid: 10,
    name: "Aids to Navigation monitoring data",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "UK Trinity House",
    permittedAsFrom: "15/01/2009",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('seqno', 'Sequence Number', 2),
      AsmField('dest_mmsi', 'Destination MMSI', 30),
      AsmField('retransmit', 'Retransmit flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('ana_int', 'Analogue', 10),
      AsmField('ana_ext1', 'Analogue (ext. #1)', 10),
      AsmField('ana_ext2', 'Analogue (ext. #2)', 10),
      AsmField('racon', 'RACON status', 2),
      AsmField('light', 'Light status', 2),
      AsmField('health', 'Health', 1),
      AsmField('stat_ext', 'Status (external)', 8),
      AsmField('off_pos', 'Position status', 1),
      AsmField('spare', 'Spare', 4),
    ],
  ),  AsmFormat(
    dac: 316,
    fid: 1,
    name: "Weather Station Message",
    types: [6],
    sub: 1,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 316,
    fid: 1,
    name: "Wind Information Message",
    types: [6],
    sub: 2,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 316,
    fid: 1,
    name: "Water Level Message",
    types: [6],
    sub: 3,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 316,
    fid: 1,
    name: "Water Flow Message (Seaway)",
    types: [6],
    sub: 6,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 316,
    fid: 2,
    name: "Lockage Order Message (Seaway)",
    types: [6],
    sub: 1,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
  ),  AsmFormat(
    dac: 316,
    fid: 2,
    name: "Estimated Lock Times Message (Seaway)",
    types: [6],
    sub: 2,
    version: 3,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
  ),  AsmFormat(
    dac: 316,
    fid: 32,
    name: "Version Message (Seaway)",
    types: [6],
    sub: 1,
    version: 1,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('major_version', 'Major Version', 8),
      AsmField('minor_version', 'Minor Version', 8),
      AsmField('reserved', 'Reserved', 8),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 1,
    name: "Weather Station Message",
    types: [6],
    sub: 1,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 1,
    name: "Wind Information Message",
    types: [6],
    sub: 2,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 1,
    name: "Water Level Message",
    types: [6],
    sub: 3,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 1,
    name: "Water Flow Message (Seaway)",
    types: [6],
    sub: 6,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 2,
    name: "Lockage Order Message (Seaway)",
    types: [6],
    sub: 1,
    version: 5,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('timetag', 'Timetag', 20),
      AsmField('lock_id', 'Lock ID', 42, kind: AsmFieldKind.text6),
      AsmField('longitude', 'Longitude', 25),
      AsmField('latitude', 'Latitude', 24),
      AsmField('reserved', 'Reserved', 9),
      AsmField('lock_schedule', 'Lock Schedule', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 2,
    name: "Estimated Lock Times Message (Seaway)",
    types: [6],
    sub: 2,
    version: 3,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('timetag', 'Timetag', 20),
      AsmField('vessel_name', 'Vessel Name', 90, kind: AsmFieldKind.text6),
      AsmField('last_location', 'Last Location', 42, kind: AsmFieldKind.text6),
      AsmField('last_ata', 'Last ATA', 20),
      AsmField('first_lock', 'First Lock', 42, kind: AsmFieldKind.text6),
      AsmField('first_lock_eta', 'First Lock ETA', 20),
      AsmField('second_lock', 'Second Lock', 42, kind: AsmFieldKind.text6),
      AsmField('second_lock_eta', 'Second Lock ETA', 20),
      AsmField('delay', 'Delay', 42),
      AsmField('reserved', 'Reserved', 4),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 32,
    name: "Version Message (Seaway)",
    types: [6],
    sub: 1,
    version: 1,
    state: AsmState.inForce,
    registrant: "Saint Lawrence Seaway Development Corporation",
    permittedAsFrom: "09/03/2002",
    fields: [
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('major_version', 'Major Version', 8),
      AsmField('minor_version', 'Minor Version', 8),
      AsmField('reserved', 'Reserved', 8),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 55,
    name: "Text Message Payload",
    types: [6],
    sub: 5,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 366,
    fid: 58,
    name: "Target Of Interest",
    types: [6],
    sub: 2,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('dac', 'DAC', 10),
      AsmField('function_id', 'Function ID', 6),
      AsmField('source_id_mmsi', 'Source ID (MMSI)', 30),
      AsmField('target_type', 'Target Type', 4),
      AsmField('target_id', 'Target ID', 30),
    ],
  ),  AsmFormat(
    dac: 367,
    fid: 16,
    name: "Passenger and Crew Count",
    types: [6],
    sub: 1,
    state: AsmState.draft,
    registrant: "USCG RDC",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('message_version', 'Message Version', 6),
      AsmField('utc_day', 'UTC day', 5),
    ],
  ),  AsmFormat(
    dac: 421,
    fid: 16,
    name: "Collision alarm",
    types: [6],
    sub: 1,
    state: AsmState.testing,
    registrant: "Sena and Vans Co., Ltd",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('sequence_number', 'Sequence Number', 2),
      AsmField('destination_id', 'Destination ID', 30),
      AsmField('retransmit_flag', 'Retransmit Flag', 1),
      AsmField('spare', 'Spare', 1),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('sub_function_identifier', 'Sub Function Identifier', 16),
      AsmField('direction', 'Direction', 12),
      AsmField('distance', 'Distance', 10),
      AsmField('warning_level', 'Warning Level', 2),
      AsmField('arrival_time', 'Arrival Time', 8),
      AsmField('spare_1', 'Spare', 4),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 0,
    name: "Text telegram using 6-bit ASCII",
    types: [8],
    fields: _kTextMsgFields,
    sub: 5,
    state: AsmState.replaced,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
    notToBeUsedAfter: "15/06/2007",
    deprecatedSince: "not to be used after 15/06/2007",
  ),  AsmFormat(
    dac: 1,
    fid: 0,
    name: "Text using 6-bit ASCII",
    types: [8],
    fields: _kTextMsgFields,
    sub: 5,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-3",
    permittedAsFrom: "16/06/2007",
  ),  AsmFormat(
    dac: 1,
    fid: 11,
    name: "Metreorological and hydrological data",
    types: [8],
    sub: 2,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "16/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('day', 'Day (UTC)', 5),
      AsmField('hour', 'Hour (UTC)', 5),
      AsmField('minute', 'Minute (UTC)', 6),
      AsmField('wspeed', 'Average Wind Speed', 7),
      AsmField('wgust', 'Gust Speed', 7),
      AsmField('wdir', 'Wind Direction', 9),
      AsmField('wgustdir', 'Wind Gust Direction', 9),
      AsmField('temperature', 'Air Temperature', 11),
      AsmField('humidity', 'Relative Humidity', 7),
      AsmField('dewpoint', 'Dew Point', 10),
      AsmField('pressure', 'Air Pressure', 9),
      AsmField('pressuretend', 'Pressure Tendency', 2),
      AsmField('visibility', 'Horiz. Visibility', 8),
      AsmField('waterlevel', 'Water Level', 9, kind: AsmFieldKind.signed),
      AsmField('leveltrend', 'Water Level Trend', 2),
      AsmField('cspeed', 'Surface Current Speed', 8),
      AsmField('cdir', 'Surface Current Direction', 9),
      AsmField('cspeed2', 'Current Speed #2', 8),
      AsmField('cdir2', 'Current Direction #2', 9),
      AsmField('cdepth2', 'Measurement Depth #2', 5),
      AsmField('cspeed3', 'Current Speed #3', 8),
      AsmField('cdir3', 'Current Direction #3', 9),
      AsmField('cdepth3', 'Measurement Depth #3', 5),
      AsmField('waveheight', 'Wave height', 8),
      AsmField('waveperiod', 'Wave period', 6),
      AsmField('wavedir', 'Wave direction', 9),
      AsmField('swellheight', 'Swell height', 8),
      AsmField('swellperiod', 'Swell period', 6),
      AsmField('swelldir', 'Swell direction', 9),
      AsmField('seastate', 'Sea state', 4),
      AsmField('watertemp', 'Water Temperature', 10),
      AsmField('preciptype', 'Precipitation', 3),
      AsmField('salinity', 'Salinity', 9),
      AsmField('ice', 'Ice', 2),
      AsmField('spare', 'Spare', 6),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 13,
    name: "Fairway closed",
    types: [8],
    sub: 3,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "17/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('reason', 'Reason For Closing', 120, kind: AsmFieldKind.text6),
      AsmField('closefrom', 'Location Of Closing From', 120, kind: AsmFieldKind.text6),
      AsmField('closeto', 'Location of Closing To', 120, kind: AsmFieldKind.text6),
      AsmField('radius', 'Radius extension', 10),
      AsmField('extunit', 'Unit of extension', 2),
      AsmField('fday', 'From day (UTC)', 5),
      AsmField('fmonth', 'From month (UTC)', 4),
      AsmField('fhour', 'From hour (UTC)', 5),
      AsmField('fminute', 'From minute (UTC)', 6),
      AsmField('tday', 'To day (UTC)', 5),
      AsmField('tmonth', 'To month (UTC)', 4),
      AsmField('thour', 'To hour (UTC)', 5),
      AsmField('tminute', 'To minute (UTC)', 6),
      AsmField('spare', 'Spare', 4),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 15,
    name: "Extended ship static and voyage related data",
    types: [8],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "19/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('airdraught', 'Air Draught', 11),
      AsmField('spare', 'Spare', 5),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 16,
    name: "VTS targets (targets derived by means other than AIS)",
    types: [8],
    sub: 1,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
  ),  AsmFormat(
    dac: 1,
    fid: 17,
    name: "Pseudo-AIS targets",
    types: [8],
    sub: 3,
    state: AsmState.deprecated,
    registrant: "IMO Circ. 236",
    permittedAsFrom: "19/05/2004",
    notToBeUsedAfter: "01/01/2013",
    deprecatedSince: "not to be used after 01/01/2013",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('idtype', 'Identifier type', 2),
      AsmField('id', 'Target identifier', 42),
      AsmField('spare', 'Spare', 4),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('course', 'Course Over Ground', 9),
      AsmField('second', 'Time Stamp', 6),
      AsmField('speed', 'Speed Over Ground', 10),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 17,
    name: "VTS-generated/Synthetic targets",
    types: [8],
    sub: 3,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('idtype', 'Identifier type', 2),
      AsmField('id', 'Target identifier', 42),
      AsmField('spare', 'Spare', 4),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('course', 'Course Over Ground', 9),
      AsmField('second', 'Time Stamp', 6),
      AsmField('speed', 'Speed Over Ground', 10),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 18,
    name: "Advice of waypoints (AWP) and/or route plan of VTS",
    types: [8],
    sub: 5,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-1",
    permittedAsFrom: "01/01/1998",
  ),  AsmFormat(
    dac: 1,
    fid: 19,
    name: "Marine traffic signal",
    types: [8],
    sub: 2,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('linkage', 'Message Linkage ID', 10),
      AsmField('station', 'Name of Signal Station', 120, kind: AsmFieldKind.text6),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('status', 'Status of Signal', 2),
      AsmField('signal', 'Signal In Service', 5),
      AsmField('hour', 'UTC hour', 5),
      AsmField('minute', 'UTC minute', 6),
      AsmField('nextsignal', 'Expected Next Signal', 5),
      AsmField('spare', 'Spare', 102),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 21,
    name: "Weather observation report from ship",
    types: [8],
    sub: 2,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('wmo', 'Variant', 1),
      AsmField('location', 'Location', 120, kind: AsmFieldKind.text6),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('day', 'UTC Day', 5),
      AsmField('hour', 'UTC hour', 5),
      AsmField('minute', 'UTC minute', 6),
      AsmField('weather', 'Present Weather', 4),
      AsmField('vislimit', 'Visibility Limit', 1),
      AsmField('visibility', 'Horiz. Visibility', 7),
      AsmField('humidity', 'Relative Humidity', 7),
      AsmField('wspeed', 'Average Wind Speed', 7),
      AsmField('wdir', 'Wind Direction', 9),
      AsmField('pressure', 'Air Pressure', 9),
      AsmField('pressuretend', 'Pressure Tendency', 4),
      AsmField('airtemp', 'Air Temperature', 11, kind: AsmFieldKind.signed),
      AsmField('watertemp', 'Water Temperature', 10, kind: AsmFieldKind.signed),
      AsmField('waveperiod', 'Wave period', 6),
      AsmField('waveheight', 'Wave height', 8),
      AsmField('wavedir', 'Wave direction', 9),
      AsmField('swellheight', 'Swell height', 8),
      AsmField('swelldir', 'Swell direction', 9),
      AsmField('swellperiod', 'Swell period', 6),
      AsmField('spare', 'Spare', 3),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 22,
    name: "Area notice",
    types: [8],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "04/03/2011",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('linkage', 'Message Linkage ID', 10),
      AsmField('notice', 'Notice Description', 7),
      AsmField('month', 'Month (UTC)', 4),
      AsmField('day', 'Day (UTC)', 5),
      AsmField('hour', 'Hour (UTC)', 5),
      AsmField('minute', 'Minute (UTC)', 6),
      AsmField('duration', 'Duration', 18),
      AsmField('subarea_type', 'Subarea shape #1', 3),
      AsmField('subarea_type', 'Subarea shape #2', 3),
      AsmField('subarea_type', 'Subarea shape #3', 3),
      AsmField('subarea_type', 'Subarea shape #4', 3),
      AsmField('subarea_type', 'Subarea shape #5', 3),
      AsmField('subarea_type', 'Subarea shape #6', 3),
      AsmField('subarea_type', 'Subarea shape #7', 3),
      AsmField('subarea_type', 'Subarea shape #8', 3),
      AsmField('subarea_type', 'Subarea shape #9', 3),
      AsmField('subarea_type', 'Subarea shape #10', 3),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 24,
    name: "Extended ship static and voyage-related data",
    types: [8],
    sub: 2,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('linkage', 'Message Linkage ID', 10),
      AsmField('airdraught', 'Air Draught', 13),
      AsmField('lastport', 'Last Port Of Call', 30, kind: AsmFieldKind.text6),
      AsmField('nextport', 'Next Port Of Call', 30, kind: AsmFieldKind.text6),
      AsmField('secondport', 'Second Port Of Call', 30, kind: AsmFieldKind.text6),
      AsmField('ais_state', 'AIS Class A', 2),
      AsmField('ata_state', 'Automatic Tracking Aid', 2),
      AsmField('bnwas_state', 'BNWAS', 2),
      AsmField('ecdisb_state', 'ECDIS Back-up', 2),
      AsmField('chart_state', 'Paper Nautical Chart', 2),
      AsmField('sounder_state', 'Echo sounder', 2),
      AsmField('epaid_state', 'Electronic plotting aid', 2),
      AsmField('steer_state', 'Emergency steering gear', 2),
      AsmField('gnss_state', 'GNSS', 2),
      AsmField('gyro_state', 'Gyro compass', 2),
      AsmField('lrit_state', 'LRIT', 2),
      AsmField('magcomp_state', 'Magnetic compass', 2),
      AsmField('navtex_state', 'NAVTEX', 2),
      AsmField('arpa_state', 'Radar (ARPA)', 2),
      AsmField('sband_state', 'Radar (S-band)', 2),
      AsmField('xband_state', 'Radar (X-band)', 2),
      AsmField('hfradio_state', 'Radio HF', 2),
      AsmField('inmarsat_state', 'Radio INMARSAT', 2),
      AsmField('mfradio_state', 'Radio MF', 2),
      AsmField('vhfradio_state', 'Radio VHF', 2),
      AsmField('grndlog_state', 'Speed Log over ground', 2),
      AsmField('waterlog_state', 'Speed Log through water', 2),
      AsmField('thd_state', 'THD', 2),
      AsmField('tcs_state', 'Track control system', 2),
      AsmField('vdr_state', 'VDR/S-VDR', 2),
      AsmField('reserved', 'Reserved', 2),
      AsmField('iceclass', 'Ice Class', 4),
      AsmField('horsepower', 'Shaft Horsepower', 18),
      AsmField('vhfchan', 'VHF Working Channel', 12),
      AsmField('lshiptype', 'Lloyd’s Ship Type', 42, kind: AsmFieldKind.text6),
      AsmField('tonnage', 'Gross Tonnage', 18),
      AsmField('lading', 'Laden or Ballast', 2),
      AsmField('heavyoil', 'Heavy Fuel Oil Bunkered', 2),
      AsmField('lightoil', 'Light Fuel Oil Bunkered', 2),
      AsmField('dieseloil', 'Diesel Oil Bunkered', 2),
      AsmField('totaloil', 'Total Bunker Oil', 14),
      AsmField('persons', 'Number of persons', 13),
      AsmField('spare', 'Spare', 10),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 26,
    name: "Environmental",
    types: [8],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('sensor', 'Sensor Report Type', 4),
      AsmField('day', 'Day (UTC)', 5),
      AsmField('hour', 'Hour (UTC)', 5),
      AsmField('minute', 'Minute (UTC)', 6),
      AsmField('site', 'Site ID', 7),
      AsmField('payload', 'Sensor payload', 85, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 27,
    name: "Route information",
    types: [8],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('linkage', 'Message Linkage ID', 10),
      AsmField('sender', 'Sender Class', 3),
      AsmField('rtype', 'Route Type', 5),
      AsmField('month', 'Start month', 4),
      AsmField('day', 'Start day', 5),
      AsmField('hour', 'Start hour', 5),
      AsmField('minute', 'Start minute', 6),
      AsmField('duration', 'Duration', 18),
      AsmField('waycount', 'Waypoint count', 5),
      AsmField('lon', 'Longitude', 28, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 27, kind: AsmFieldKind.signed),
    ],
  ),  AsmFormat(
    dac: 1,
    fid: 29,
    name: "Text description",
    types: [8],
    sub: 5,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 1,
    fid: 31,
    name: "Meteorological and Hydrographic data",
    types: [8],
    sub: 2,
    state: AsmState.inForce,
    registrant: "IMO Circ. 289",
    permittedAsFrom: "01/06/2010",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fid', 'FID', 6),
      AsmField('lon', 'Longitude', 25, kind: AsmFieldKind.signed),
      AsmField('lat', 'Latitude', 24, kind: AsmFieldKind.signed),
      AsmField('accuracy', 'Fix quality', 1),
      AsmField('day', 'Day', 5),
      AsmField('hour', 'Hour', 5),
      AsmField('minute', 'Minute', 6),
      AsmField('wspeed', 'Average Wind Speed', 7),
      AsmField('wgust', 'Gust Speed', 7),
      AsmField('wdir', 'Wind Direction', 9),
      AsmField('wgustdir', 'Wind Gust Direction', 9),
      AsmField('airtemp', 'Air Temperature', 11, kind: AsmFieldKind.signed),
      AsmField('humidity', 'Relative Humidity', 7),
      AsmField('dewpoint', 'Dew Point', 10, kind: AsmFieldKind.signed),
      AsmField('pressure', 'Air Pressure', 9),
      AsmField('pressuretend', 'Pressure Tendency', 2),
      AsmField('visgreater', 'Max. visibility', 7),
      AsmField('visibility', 'Horiz. Visibility', 8),
      AsmField('waterlevel', 'Water Level', 12, kind: AsmFieldKind.signed),
      AsmField('leveltrend', 'Water Level Trend', 2),
      AsmField('cspeed', 'Surface Current Speed', 8),
      AsmField('cdir', 'Surface Current Direction', 9),
      AsmField('cspeed2', 'Current Speed #2', 8),
      AsmField('cdir2', 'Current Direction #2', 9),
      AsmField('cdepth2', 'Measurement Depth #2', 5),
      AsmField('cspeed3', 'Current Speed #3', 8),
      AsmField('cdir3', 'Current Direction #3', 9),
      AsmField('cdepth3', 'Measurement Depth #3', 5),
      AsmField('waveheight', 'Wave Height', 8),
      AsmField('waveperiod', 'Wave Period', 6),
      AsmField('wavedir', 'Wave Direction', 9),
      AsmField('swellheight', 'Swell Height', 8),
      AsmField('swellperiod', 'Swell Period', 6),
      AsmField('swelldir', 'Swell Direction', 9),
      AsmField('seastate', 'Sea State', 4),
      AsmField('watertemp', 'Water Temperature', 10, kind: AsmFieldKind.signed),
      AsmField('preciptype', 'Precipitation', 3),
      AsmField('salinity', 'Salinity', 9),
      AsmField('ice', 'Ice', 2),
      AsmField('spare', 'Spare', 10),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 1,
    name: "Control Message",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "01/12/2017",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 0, kind: AsmFieldKind.data),
      AsmField('source_id', 'Source ID', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 10,
    name: "Inland ship static and voyage related data",
    types: [8],
    sub: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'Designated Area Code', 10),
      AsmField('fid', 'Functional ID', 6),
      AsmField('vin', 'European Vessel ID', 48, kind: AsmFieldKind.text6),
      AsmField('length', 'Length of ship', 13),
      AsmField('beam', 'Beam of ship', 10),
      AsmField('shiptype', 'Ship/combination type', 14),
      AsmField('hazard', 'Hazardous cargo', 3),
      AsmField('draught', 'Draught', 11),
      AsmField('loaded', 'Loaded/Unloaded', 2),
      AsmField('speed_q', 'Speed inf. quality', 1),
      AsmField('course_q', 'Course inf. quality', 1),
      AsmField('heading_q', 'Heading inf. quality', 1),
      AsmField('spare', 'Spare', 8),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 11,
    name: "Convoy message",
    types: [8],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "06/06/2014",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
      AsmField('n', 'N', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 23,
    name: "EMMA warning",
    types: [8],
    sub: 2,
    state: AsmState.discontinued,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
    fields: [
      AsmField('type', 'Message Type', 6),
      AsmField('repeat', 'Repeat Indicator', 2),
      AsmField('mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'Designated Area Code', 10),
      AsmField('fid', 'Functional ID', 6),
      AsmField('start_year', 'Start Year', 8),
      AsmField('start_month', 'Start Month', 4),
      AsmField('start_day', 'Start Day', 5),
      AsmField('end_year', 'End Year', 8),
      AsmField('end_month', 'End Month', 4),
      AsmField('end_day', 'End Day', 5),
      AsmField('start_hour', 'Start Hour', 5),
      AsmField('start_minute', 'Start Minute', 6),
      AsmField('end_hour', 'End Hour', 5),
      AsmField('end_minute', 'End Minute', 6),
      AsmField('start_lon', 'Start Longitude', 28, kind: AsmFieldKind.signed),
      AsmField('start_lat', 'Start Latitude', 27, kind: AsmFieldKind.signed),
      AsmField('end_lon', 'End Longitude', 28, kind: AsmFieldKind.signed),
      AsmField('end_lat', 'End Latitude', 27, kind: AsmFieldKind.signed),
      AsmField('type', 'Type', 4),
      AsmField('min', 'Min value', 9, kind: AsmFieldKind.signed),
      AsmField('max', 'Max value', 9, kind: AsmFieldKind.signed),
      AsmField('intensity', 'Classification', 2),
      AsmField('wind', 'Wind Direction', 4),
      AsmField('spare', 'Spare', 6),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 24,
    name: "Water level message",
    types: [8],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
    notToBeUsedAfter: "18/10/2021",
    deprecatedSince: "not to be used after 18/10/2021",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 0, kind: AsmFieldKind.data),
      AsmField('source_id', 'Source ID', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 25,
    name: "Present Bridge Clearance",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.deprecated,
    registrant: "EU",
    permittedAsFrom: "01/12/2016",
    notToBeUsedAfter: "18/10/2022",
    deprecatedSince: "not to be used after 18/10/2022",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 0, kind: AsmFieldKind.data),
      AsmField('source_id', 'Source ID', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 25,
    name: "Present Bridge Clearance",
    types: [8],
    sub: 1,
    version: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "18/10/2021",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 0, kind: AsmFieldKind.data),
      AsmField('source_id', 'Source ID', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 26,
    name: "Water level message",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "18/10/2020",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 0, kind: AsmFieldKind.data),
      AsmField('source_id', 'Source ID', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 40,
    name: "Signal status",
    types: [8],
    sub: 1,
    state: AsmState.replaced,
    registrant: "EU",
    permittedAsFrom: "10/10/2007",
  ),  AsmFormat(
    dac: 200,
    fid: 41,
    name: "Signal Station",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.inForce,
    registrant: "EU",
    permittedAsFrom: "24/11/2016",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 0, kind: AsmFieldKind.data),
      AsmField('source_id', 'Source ID', 0, kind: AsmFieldKind.data),
      AsmField('spare', 'Spare', 0, kind: AsmFieldKind.data),
      AsmField('application_identifier', 'Application Identifier', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 42,
    name: "Geographic Notice",
    types: [8],
    sub: 0,
    version: 5,
    state: AsmState.proposal,
    registrant: "EU",
    permittedAsFrom: "25/06/2020",
    fields: [
      AsmField('message_id', 'Message ID', 0, kind: AsmFieldKind.data),
      AsmField('designated_area_code', 'Designated Area Code', 0, kind: AsmFieldKind.data),
      AsmField('utc_month', 'UTC month', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 200,
    fid: 44,
    name: "ISRS Text message",
    types: [8],
    sub: 0,
    version: 3,
    state: AsmState.proposal,
    registrant: "EU",
    permittedAsFrom: "25/06/2020",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 218,
    fid: 1,
    name: "Forward to Vessel Position Information Server (VPI)",
    types: [6, 8],
    sub: 0,
    version: 1,
    state: AsmState.testing,
    registrant: "CoRISMa (EU project)",
    permittedAsFrom: "16/06/2015",
    notToBeUsedAfter: "01/01/2016",
  ),  AsmFormat(
    dac: 219,
    fid: 1,
    name: "Intended route",
    types: [8],
    sub: 3,
    state: AsmState.draft,
    registrant: "Danish Maritime Authority",
    permittedAsFrom: "03/11/2011",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('spare', 'Spare', 1),
      AsmField('iai', 'IAI', 16),
      AsmField('eta_active_wp', 'ETA active WP', 0, kind: AsmFieldKind.data),
      AsmField('utc_month', 'UTC Month', 4),
      AsmField('utc_day', 'UTC Day', 5),
      AsmField('utc_hour', 'UTC Hour', 5),
      AsmField('utc_minute', 'UTC Minute', 6),
      AsmField('duration', 'Duration', 18),
      AsmField('number_of_waypoints', 'Number of Waypoints', 5),
      AsmField('waypoints', 'Waypoints', 0, kind: AsmFieldKind.data),
      AsmField('spare_1', 'Spare', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 219,
    fid: 4,
    name: "Tactical voyageplan broadcast, extended",
    types: [8],
    sub: 5,
    state: AsmState.proposal,
    registrant: "Danish Maritime Authority",
    permittedAsFrom: "04/02/2015",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('iai', 'IAI', 16),
    ],
  ),  AsmFormat(
    dac: 224,
    fid: 50,
    name: "Envelope/volume",
    types: [8],
    sub: 5,
    state: AsmState.draft,
    registrant: "GMV",
    permittedAsFrom: "01/01/2013",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('hour_generation', 'Hour Generation', 5),
      AsmField('minute_generation', 'Minute Generation', 6),
      AsmField('second_generation', 'Second Generation', 6),
      AsmField('geometry_aft', 'Geometry Aft', 2),
      AsmField('geometry_bow', 'Geometry Bow', 2),
      AsmField('geometry_curve', 'Geometry Curve', 2),
      AsmField('geometry_3d_above_wl', 'Geometry 3D Above WL', 2),
      AsmField('geometry_3d_under_wl', 'Geometry 3D Under WL', 2),
      AsmField('longitude_point_1', 'Longitude Point 1', 28),
      AsmField('latitude_point_1', 'Latitude Point 1', 27),
      AsmField('longitude_point_2', 'Longitude Point 2*', 28),
      AsmField('latitude_point_2', 'Latitude Point 2*', 27),
      AsmField('longitude_point_3', 'Longitude Point 3', 28),
      AsmField('latitude_point_3', 'Latitude Point 3', 27),
      AsmField('longitude_point_4', 'Longitude Point 4*', 28),
      AsmField('latitude_point_4', 'Latitude Point 4*', 27),
      AsmField('longitude_point_5', 'Longitude Point 5', 28),
      AsmField('latitude_point_5', 'Latitude Point 5', 27),
      AsmField('longitude_point_6', 'Longitude Point 6', 28),
      AsmField('latitude_point_6', 'Latitude Point 6', 27),
      AsmField('longitude_point_7', 'Longitude Point 7', 28),
      AsmField('latitude_point_7', 'Latitude Point 7', 27),
      AsmField('longitude_point_8', 'Longitude Point 8', 28),
      AsmField('latitude_point_8', 'Latitude Point 8', 27),
      AsmField('longitude_point_9', 'Longitude Point 9', 28),
      AsmField('latitude_point_9', 'Latitude Point 9', 27),
      AsmField('longitude_point_10', 'Longitude Point 10', 28),
      AsmField('latitude_point_10', 'Latitude Point 10', 27),
      AsmField('altitude_point_10', 'Altitude Point 10', 17),
      AsmField('longitude_point_11', 'Longitude Point 11', 28),
      AsmField('latitude_point_11', 'Latitude Point 11', 27),
      AsmField('altitude_point_11', 'Altitude Point 11', 17),
      AsmField('longitude_point_12', 'Longitude Point 12**', 28),
      AsmField('latitude_point_12', 'Latitude Point 12**', 27),
      AsmField('altitude_point_12', 'Altitude Point 12**', 17),
      AsmField('longitude_point_13', 'Longitude Point 13', 28),
      AsmField('latitude_point_13', 'Latitude Point 13', 27),
      AsmField('altitude_point_13', 'Altitude Point 13', 17),
      AsmField('longitude_point_14', 'Longitude Point 14', 28),
      AsmField('latitude_point_14', 'Latitude Point 14', 27),
      AsmField('altitude_point_14', 'Altitude Point 14', 17),
    ],
  ),  AsmFormat(
    dac: 246,
    fid: 12,
    name: "Route intension sharing",
    types: [8],
    sub: 0,
    version: 3,
    state: AsmState.testing,
    registrant: "Rijkswaterstaat Netherlands",
    permittedAsFrom: "07/07/2025",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('spare', '(spare)', 2),
      AsmField('application_identifier', 'Application Identifier', 16),
      AsmField('version', 'Version', 3),
      AsmField('intention_source', 'Intention Source', 3),
      AsmField('intention_reliability', 'Intention Reliability', 2),
      AsmField('testmessage', 'Testmessage', 1),
      AsmField('update_time', 'Update Time', 17),
      AsmField('number_of_waypoints', 'Number of Waypoints', 4),
      AsmField('waypoint_1', 'Waypoint 1', 0, kind: AsmFieldKind.data),
      AsmField('waypoints_2_9_delta', 'Waypoints 2 – 9 delta', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 265,
    fid: 1,
    name: "Route Message",
    types: [8],
    sub: 3,
    state: AsmState.inForce,
    registrant: "STM project (Sweden)",
    permittedAsFrom: "03/03/2016",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('repeat_indicator', 'Repeat indicator', 2),
      AsmField('source_id', 'Source ID', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('dac', 'DAC', 10),
      AsmField('fi', 'FI', 6),
      AsmField('first_waypoint_type', 'First waypoint type', 1),
      AsmField('first_waypoint_longitude', 'First waypoint longitude', 28),
      AsmField('first_waypoint_latitude', 'First waypoint latitude', 27),
      AsmField('intermediate_legs', 'Intermediate legs', 0, kind: AsmFieldKind.data),
      AsmField('leg_geometry', 'Leg geometry', 1),
      AsmField('planned_speed', 'Planned speed', 10),
      AsmField('turn_radius', 'Turn radius', 9),
      AsmField('longitude_delta', 'Longitude delta', 22),
      AsmField('latitude_delta', 'Latitude delta', 22),
      AsmField('final_reported_leg', 'Final reported leg', 0, kind: AsmFieldKind.data),
      AsmField('leg_geometry_1', 'Leg geometry', 1),
      AsmField('planned_speed_1', 'Planned speed', 10),
      AsmField('last_waypoint_longitude', 'Last waypoint longitude', 28),
      AsmField('last_waypoint_latitude', 'Last waypoint latitude', 27),
      AsmField('steering_mode', 'Steering mode', 2),
      AsmField('spare_1', 'Spare', 4),
    ],
  ),  AsmFormat(
    dac: 265,
    fid: 6,
    name: "Route Message",
    types: [8],
    sub: 3,
    state: AsmState.inForce,
    registrant: "Danish Maritime Authority",
    permittedAsFrom: "03/03/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 14,
    name: "SAR Pattern Report (Unencrypted)",
    types: [8],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 16,
    name: "Trackline Report (Unencrypted)",
    types: [8],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 19,
    name: "Lock Status",
    types: [8],
    sub: 0,
    version: 2,
    state: AsmState.draft,
    registrant: "USCG RDC",
    permittedAsFrom: "01/10/2015",
  ),  AsmFormat(
    dac: 366,
    fid: 22,
    name: "Area Notice",
    types: [8],
    sub: 5,
    state: AsmState.deprecated,
    registrant: "USCG RDC",
    permittedAsFrom: "12/04/2011",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('message_linkage_id', 'Message Linkage ID', 10, kind: AsmFieldKind.text6),
      AsmField('utc_month', 'UTC month', 4),
      AsmField('1_7', '1-7', 0, kind: AsmFieldKind.data),
      AsmField('208_1016', '208 – 1016', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 33,
    name: "Environmental Message",
    types: [8],
    sub: 5,
    state: AsmState.deprecated,
    registrant: "USCG RDC",
    permittedAsFrom: "19/04/2011",
    notToBeUsedAfter: "01/01/2014",
    deprecatedSince: "not to be used after 01/01/2014",
    fields: [
      AsmField('standard_message_header', 'Standard Message Header', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('binary_data', 'Binary Data', 0, kind: AsmFieldKind.data),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('application_data', 'Application Data', 0, kind: AsmFieldKind.data),
      AsmField('sensor_report_2', 'Sensor Report 2', 112),
      AsmField('sensor_report_3', 'Sensor Report 3', 112),
      AsmField('sensor_report_4', 'Sensor Report 4', 112),
      AsmField('sensor_report_5', 'Sensor Report 5', 112),
      AsmField('sensor_report_6', 'Sensor Report 6', 112),
      AsmField('sensor_report_7', 'Sensor Report 7', 112),
      AsmField('sensor_report_8', 'Sensor Report 8', 112),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 35,
    name: "Waterways Management",
    types: [8],
    sub: 3,
    state: AsmState.deprecated,
    registrant: "USCG RDC",
    permittedAsFrom: "12/04/2011",
    fields: [
      AsmField('message_id', 'Message ID', 6),
      AsmField('designated_area_code', 'Designated Area Code', 10),
      AsmField('message_linkage_id', 'Message Linkage ID', 10),
      AsmField('128_520', '128 - 520', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 55,
    name: "Text Message Payload",
    types: [8],
    sub: 2,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 366,
    fid: 56,
    name: "Position Report Payload",
    types: [8],
    sub: 3,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    notToBeUsedAfter: "20/04/2017",
    deprecatedSince: "not to be used after 20/04/2017",
    fields: [
      AsmField('dac', 'DAC', 10),
      AsmField('function_id', 'Function ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 0),
      AsmField('user_id', 'User ID', 30),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 57,
    name: "Static Data Payload",
    types: [8],
    sub: 3,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    notToBeUsedAfter: "20/04/2017",
    deprecatedSince: "not to be used after 20/04/2017",
    fields: [
      AsmField('dac', 'DAC', 10),
      AsmField('function_id', 'Function ID', 6),
      AsmField('repeat_indicator', 'Repeat Indicator', 0),
      AsmField('user_id', 'User ID', 30),
      AsmField('dimension_reference_for_position', 'Dimension/Reference for Position', 30),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 58,
    name: "Target Of Interest (TOI)",
    types: [8],
    sub: 2,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('dac', 'DAC', 10),
      AsmField('function_id', 'Function ID', 6),
      AsmField('source_id_mmsi', 'Source ID (MMSI)', 30),
      AsmField('target_type', 'Target Type', 4),
      AsmField('target_id', 'Target ID', 30),
    ],
  ),  AsmFormat(
    dac: 367,
    fid: 22,
    name: "Geographic Notice",
    types: [8],
    sub: 2,
    version: 5,
    state: AsmState.testing,
    registrant: "USCG RDC",
  ),  AsmFormat(
    dac: 367,
    fid: 23,
    name: "Satellite Ship Weather",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.draft,
    registrant: "USACE",
    permittedAsFrom: "01/10/2019",
    fields: [
      AsmField('standard_message_header', 'Standard Message Header', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('binary_data', 'Binary Data', 0, kind: AsmFieldKind.data),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('application_data', 'Application Data', 0, kind: AsmFieldKind.data),
      AsmField('utc_day', 'UTC day', 5),
      AsmField('utc_hour', 'UTC hour', 5),
      AsmField('utc_minute', 'UTC minute', 6),
      AsmField('longitude', 'Longitude', 25),
      AsmField('latitude', 'Latitude', 24),
      AsmField('air_pressure', 'Air Pressure', 9),
      AsmField('air_temperature', 'Air Temperature', 11),
      AsmField('wind_speed', 'Wind Speed', 7),
      AsmField('wind_gust', 'Wind Gust', 7),
      AsmField('wind_direction', 'Wind Direction', 9),
      AsmField('spare_1', 'Spare', 1),
    ],
  ),  AsmFormat(
    dac: 367,
    fid: 24,
    name: "Satellite Ship Weather Small",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.draft,
    registrant: "USACE",
    permittedAsFrom: "01/10/2019",
    fields: [
      AsmField('standard_message_header', 'Standard Message Header', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('binary_data', 'Binary Data', 0, kind: AsmFieldKind.data),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('utc_hour', 'UTC hour', 5),
      AsmField('utc_minute', 'UTC minute', 6),
      AsmField('longitude', 'Longitude', 25),
      AsmField('latitude', 'Latitude', 24),
      AsmField('air_pressure', 'Air Pressure', 9),
      AsmField('spare_1', 'Spare', 0),
    ],
  ),  AsmFormat(
    dac: 367,
    fid: 25,
    name: "Satellite Ship Weather Tiny",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.draft,
    registrant: "USACE",
    permittedAsFrom: "01/10/2019",
    fields: [
      AsmField('standard_message_header', 'Standard Message Header', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('binary_data', 'Binary Data', 0, kind: AsmFieldKind.data),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('application_data', 'Application Data', 0, kind: AsmFieldKind.data),
      AsmField('utc_hour', 'UTC hour', 5),
      AsmField('utc_minute', 'UTC minute', 6),
      AsmField('air_pressure', 'Air Pressure', 9),
      AsmField('wind_speed', 'Wind Speed', 7),
      AsmField('wind_direction', 'Wind Direction', 9),
      AsmField('spare_1', 'Spare', 1),
    ],
  ),  AsmFormat(
    dac: 367,
    fid: 26,
    name: "GPS Jamming and Spoofing Report",
    types: [8],
    sub: 0,
    version: 1,
    state: AsmState.draft,
    registrant: "USACE",
    permittedAsFrom: "01/10/2019",
    fields: [
      AsmField('standard_message_header', 'Standard Message Header', 0, kind: AsmFieldKind.data),
      AsmField('repeat_indicator', 'Repeat Indicator', 2),
      AsmField('source_mmsi', 'Source MMSI', 30),
      AsmField('spare', 'Spare', 2),
      AsmField('binary_data', 'Binary Data', 0, kind: AsmFieldKind.data),
      AsmField('function_identifier', 'Function Identifier', 6),
      AsmField('utc_hour', 'UTC hour', 5),
      AsmField('utc_minute', 'UTC minute', 6),
      AsmField('longitude', 'Longitude', 25),
      AsmField('latitude', 'Latitude', 24),
      AsmField('type', 'Type', 1),
      AsmField('status', 'Status', 1),
      AsmField('spare_1', 'Spare', 2),
    ],
  ),  AsmFormat(
    dac: 367,
    fid: 29,
    name: "Linked Text",
    types: [8],
    sub: 1,
    version: 5,
    state: AsmState.testing,
    registrant: "USCG RDC",
    fields: _kTextMsgFields,
  ),  AsmFormat(
    dac: 367,
    fid: 33,
    name: "Environmental Message",
    types: [8],
    sub: 3,
    version: 5,
    state: AsmState.testing,
    registrant: "USCG RDC",
  ),  AsmFormat(
    dac: 367,
    fid: 35,
    name: "Waterways Management Message",
    types: [8],
    sub: 2,
    version: 3,
    state: AsmState.testing,
    registrant: "USCG RDC",
  ),  AsmFormat(
    dac: 710,
    fid: 11,
    name: "Offshore Unit Dimensions",
    types: [8],
    sub: 4,
    state: AsmState.draft,
    registrant: "PETROBRAS",
  ),  AsmFormat(
    dac: 1,
    fid: 0,
    name: "Text using 6-bit ASCII",
    types: [25],
    fields: _kTextMsgFields,
    sub: 5,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-5",
    permittedAsFrom: "01/02/2014",
  ),  AsmFormat(
    dac: 366,
    fid: 0,
    name: "Position Report for Vessels",
    types: [25],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5),
      AsmField('operating_mode', 'Operating Mode', 1),
      AsmField('navigational_status', 'Navigational Status', 4),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 1,
    name: "Static Data Report for Vessels and Aircraft",
    types: [25],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5),
      AsmField('asset_name', 'Asset Name', 96, kind: AsmFieldKind.text6),
      AsmField('asset_type', 'Asset Type', 10),
      AsmField('dte', 'DTE', 1),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 2,
    name: "Addressed Message Acknowledgement",
    types: [25],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5, kind: AsmFieldKind.text6),
      AsmField('mmsi', 'MMSI', 30),
      AsmField('hour', 'Hour', 5),
      AsmField('minute', 'Minute', 6),
      AsmField('second', 'Second', 6),
      AsmField('hour_1', 'Hour', 5),
      AsmField('minute_1', 'Minute', 6),
      AsmField('second_1', 'Second', 6),
      AsmField('unused_bits_set_to_zero', 'Unused bits set to zero', 16),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 3,
    name: "Position Report for Aircraft",
    types: [25],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5),
      AsmField('operating_mode', 'Operating Mode', 1),
      AsmField('altitude', 'Altitude', 12),
      AsmField('time_stamp', 'Time stamp', 6),
      AsmField('cog', 'COG', 9),
      AsmField('sog', 'SOG', 10),
      AsmField('communication_state_selector_flag', 'Communication state selector flag', 1),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 9,
    name: "Encrypted Message Acknowledgement",
    types: [25],
    sub: 0,
    version: 1,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 1,
    fid: 0,
    name: "Text using 6-bit ASCII",
    types: [26],
    fields: _kTextMsgFields,
    sub: 5,
    state: AsmState.inForce,
    registrant: "ITU-R.M.1371-5",
    permittedAsFrom: "01/02/2014",
  ),  AsmFormat(
    dac: 366,
    fid: 0,
    name: "Text Message, Addressed or Broadcast",
    types: [26],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5, kind: AsmFieldKind.text6),
      AsmField('hour', 'Hour', 5),
      AsmField('minute', 'Minute', 6),
      AsmField('second', 'Second', 6),
      AsmField('text_length', 'Text Length', 8, kind: AsmFieldKind.text6),
      AsmField('text', 'Text', 0, kind: AsmFieldKind.freeText),
      AsmField('unused_bits_set_to_zero', 'Unused bits set to zero', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 1,
    name: "Target of Interest (TOI), Addressed or Broadcast",
    types: [26],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5),
      AsmField('target_type', 'Target Type', 4),
      AsmField('target_id', 'Target ID', 20),
      AsmField('mmsi', 'MMSI', 30),
      AsmField('toi_status_designator', 'TOI Status Designator', 1),
      AsmField('hour', 'Hour', 5),
      AsmField('minute', 'Minute', 6),
      AsmField('second', 'Second', 6),
      AsmField('longitude', 'Longitude', 25),
      AsmField('latitude', 'Latitude', 24),
      AsmField('cog', 'COG', 9),
      AsmField('sog', 'SOG', 7),
      AsmField('length_of_text', 'Length of Text', 8, kind: AsmFieldKind.text6),
      AsmField('text', 'Text', 0, kind: AsmFieldKind.freeText),
      AsmField('unused_bits_set_to_zero', 'Unused bits set to zero', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 2,
    name: "Expanding Square, Sector, Parallel Line & Creeping Line Search & Rescue (SAR) Pattern or Circle, Overlay Option 1",
    types: [26],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5),
      AsmField('overlay_type', 'Overlay Type', 4),
      AsmField('overlay_number', 'Overlay Number', 5),
      AsmField('center_origin_longitude', 'Center/Origin Longitude', 25),
      AsmField('center_origin_latitude', 'Center/Origin Latitude', 24),
      AsmField('radius_length', 'Radius/Length', 17),
      AsmField('width', 'Width', 17),
      AsmField('orientation', 'Orientation', 9),
      AsmField('number_of_sectors', 'Number of sectors', 7),
      AsmField('track_spacing', 'Track Spacing', 14),
      AsmField('first_turn', 'First turn', 1),
      AsmField('search_speed', 'Search Speed', 10),
      AsmField('search_altitude', 'Search Altitude', 12),
      AsmField('unused_bits_set_to_zero', 'Unused bits set to zero', 90),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 3,
    name: "Track Line Search Pattern, Route or Polygon, Overlay Option 2",
    types: [26],
    sub: 1,
    state: AsmState.deprecated,
    registrant: "USCG",
    permittedAsFrom: "04/06/2014",
    fields: [
      AsmField('function_id', 'Function ID', 5),
      AsmField('overlay_type', 'Overlay Type', 4),
      AsmField('overlay_number', 'Overlay Number', 5),
      AsmField('origin_longitude', 'Origin Longitude', 25),
      AsmField('origin_latitude', 'Origin Latitude', 24),
      AsmField('number_of_additional_waypoints', 'Number of Additional Waypoints', 4),
      AsmField('search_speed', 'Search Speed', 10),
      AsmField('search_altitude', 'Search Altitude', 12),
      AsmField('unused_bits_set_to_zero', 'Unused bits set to zero', 0, kind: AsmFieldKind.data),
    ],
  ),  AsmFormat(
    dac: 366,
    fid: 13,
    name: "SAR Pattern Report (Encrypted)",
    types: [26],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 15,
    name: "Trackline Report (Encrypted)",
    types: [26],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 17,
    name: "Text Message (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 18,
    name: "Target of Interest (encrypted)",
    types: [26],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 19,
    name: "Change RSI Command (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 20,
    name: "Change RSI Response (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 21,
    name: "Changeover Command (encrypted)",
    types: [26],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 22,
    name: "Changeover Response (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 23,
    name: "Hello (encrypted)",
    types: [26],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 24,
    name: "Modify Key Command (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 25,
    name: "Negative Acknowledgement (encrypted)",
    types: [26],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 26,
    name: "Rekey Acknowledgement (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 27,
    name: "Rekey Command (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 28,
    name: "Warm-Start Command",
    types: [26],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 29,
    name: "Zeroize Command (encrypted)",
    types: [26],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 30,
    name: "Zeroize Response (encrypted)",
    types: [26],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 31,
    name: "Delete Key Command (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 32,
    name: "Delete Key Response (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 33,
    name: "Registration Command (encrypted)",
    types: [26],
    sub: 0,
    version: 4,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 34,
    name: "Registration Response (encrypted)",
    types: [26],
    sub: 0,
    version: 3,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 35,
    name: "Unable to Decrypt Response (encrypted)",
    types: [26],
    sub: 0,
    version: 4,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 36,
    name: "Area Notice (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 37,
    name: "Route Information (encrypted)",
    types: [26],
    sub: 0,
    version: 5,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "12/05/2016",
  ),  AsmFormat(
    dac: 366,
    fid: 38,
    name: "Situation Report (SITREP) for Vessels and Aircraft (encrypted)",
    types: [26],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "21/04/2017",
  ),  AsmFormat(
    dac: 366,
    fid: 39,
    name: "Static Data Report (encrypted)",
    types: [26],
    sub: 0,
    version: 2,
    state: AsmState.inForce,
    registrant: "USCG",
    permittedAsFrom: "21/04/2017",
  ),  AsmFormat(
    dac: 235,
    fid: 20,
    name: "Buoy position monitoring",
    types: [6],
    sub: 1,
    state: AsmState.inForce,
    registrant: "Trinity House",
    permittedAsFrom: "01/04/2019",
  ),  AsmFormat(
    dac: 20,
    fid: 19,
    name: "Control Message",
    types: [8],
    sub: 1,
    state: AsmState.draft,
    registrant: "EU",
  ),
];
